### PR TITLE
blog: intellij idea 2020.2 ultimate mn project

### PR DESCRIPTION
**Pull request by sdelamo**
Close: https://github.com/micronaut-projects/static-website/issues/100

@kroegerk could you review, edit and merge. Thanks!

Screenshot_2020-07-30 New Micronaut Project IntelliJ IDEA Ultimate 2020 2

### CODE REVIEW

**Comment by kroegerk** [comment]
Sergio, can you rename your image files with 2020-07-30 at the beginning of the file names, so they remain in order in the images folder?

**Comment by sdelamo** [comment]
> Sergio, can you rename your image files with 2020-07-30 at the beginning of the file names, so they remain in order in the images folder?

If I did that the url of the images will contain the date ? Do we want that?

**Comment by kroegerk** [comment]
> > Sergio, can you rename your image files with 2020-07-30 at the beginning of the file names, so they remain in order in the images folder?
> 
> If I did that the url of the images will contain the date ? Do we want that?

Yes. I think the organization benefits on our end outweigh the potential *only mildly odd* user experience. You can include your image description following the date, if you think people will want to download the images for reference. I don't think anyone will be put off by the date appearing at the beginning of the file name.

**Comment by sdelamo** [comment]
Added those dates as image prefixes.

**Pull request merged**
