### PR TITLE
Maven plugin blog post

### PR DESCRIPTION
**Pull request by alvarosanchez**
The background image is reused from other post:

Also, I don't get the `$` character to render correctly, and I didn't find a way to escape it:

### CODE REVIEW

**Comment by JasonTypesCodes** [comment]
It looks like the `$` is getting double encoded: `&amp;#36;`

**Comment by JasonTypesCodes** [comment]
This might be a bug in the md parser we are using... I'll check into that a bit

**Comment by alvarosanchez** [comment]
Also having syntax highlighting would be a great addition

**Comment by JasonTypesCodes** [comment]
This is the problem line:
https://github.com/micronaut-projects/static-website/blob/a3eb1ea18015365d07558eefd855940399e374f2/buildSrc/src/main/groovy/io/micronaut/gradle/RenderSiteTask.groovy#L274

Taking that out makes the dollar signs render correctly, however they are not escaped.  @sdelamo was that added because the MD parser isn't escaping those characters, or is there something else that requires that line?

**Comment by JasonTypesCodes** [comment]
@alvarosanchez I moved the dollar sign escaping to happen after the md has been parsed instead of before.  I believe that fixes it

**Pull request merged**
