### PR TITLE
Changes to support page

### PR DESCRIPTION
**Pull request by kroegerk**
revised introductory text; removed OCI Home to Micronaut logo; added quick-start packages per Nicki Powers request (see update Support page #23)

I didn't know how to remove the blue background from the form.

### CODE REVIEW

**Comment by sdelamo** [comment]
This is how this will look like: 

Screenshot 2020-07-30 at 09 33 03

**Comment by sdelamo** [comment]
Are we going to remove this page from OCI website and redirect it to the Micronaut site:

https://objectcomputing.com/products/micronaut/consulting-support

Are those icons in the OCI website available at SVG. 

Do you want me to try to style this page or are you ok with the above render?

**Comment by kroegerk** [comment]
I think we're going to have support pages on both websites. It is my understanding that we want to improve the experience on micronaut.io, so users are not redirected to another website quite as often.

I believe Nicki would like it to look more like the page on the OCI site, with the packages in 2 columns and the icons. Let me see if I can track down SVG versions of the icons for you.

Also, I'd like the 2 paragraphs that are currently in the right column above the form to be at the top of the left column above "The OCI team can assist you with" and the form moved up to the top of the right column.

Can you change the background on the form to white instead of blue? I can change the color of the text to black in HubSpot, so it shows up.

**Comment by kroegerk** [comment]
I uploaded two versions of the HubSpot consultation form to https://github.com/micronaut-projects/static-website-private/tree/master/main/src/main/resources

The whitebg version has black text.
The blackbg version has white text.

**Comment by kroegerk** [comment]
Here are the icons used for the Micronaut quick-start packages in SVG format. Let me know if these will work.

[micronaut-support-icons.zip](https://github.com/micronaut-projects/static-website/files/5001588/micronaut-support-icons.zip)

**Comment by sdelamo** [comment]
@kroegerk what do you think?

If you like it please, merge the PR. 

Screenshot_2020-07-31 Commercial Support Micronaut Framework

**Comment by kroegerk** [comment]
Hi Sergio!

I don't know if you got a chance to look at the pdf Nicki supplied for the page layout. I'm attaching it, along with a text description, here for reference. The text doc is a little more specific, since Nicki's pdf was just a screenshot. Let me know if you have any questions.

I provided the HubSpot form with the black text somewhere. Let me know if you cant' find it, and I'll see if I can figure out where I put it.

[support page design.pdf](https://github.com/micronaut-projects/static-website/files/5007978/support.page.design.pdf)
[support page layout.txt](https://github.com/micronaut-projects/static-website/files/5007979/support.page.layout.txt)

**Comment by kroegerk** [comment]
Found the form. I uploaded two versions of the HubSpot consultation form to https://github.com/micronaut-projects/static-website-private/tree/master/main/src/main/resources

The whitebg version has black text.
The blackbg version has white text.

Please use the whitebg version and put it on a white background.

**Comment by sdelamo** [comment]
This is how it look like: 

Screenshot_2020-08-25 Commercial Support Micronaut Framework

@kroegerk  please merge this PR if you are ok with it.

**Pull request merged**
