### PR TITLE
publishing and reviewing local changes post

### PR DESCRIPTION
**Pull request by sdelamo**
Hero image:

Screenshot 2020-08-14 at 16 50 38

blog post: 

Screenshot 2020-08-14 at 16 50 30

@kroegerk the video is unlisted in our Youtube channel. Please make it public when you publish it.

### CODE REVIEW

**Comment by ilopmar** [comment]
Switched to draft PR. The video is not the final version.

**Comment by sdelamo** [comment]
don't merge yet. we may swap the youtube video

**Comment by kroegerk** [comment]
I uploaded a featured image to the master repository, so that's ready whenever you have the final video ready.

**Comment by kroegerk** [comment]
@ilopmar This is ready for publication.

**Pull request merged**
